apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-queue-deployment
  labels:
    app: redis-queue
spec:
  selector:
    matchLabels:
      app: redis-queue
  template:
    metadata:
      labels:
        app: redis-queue
    spec:
      containers:
      - name: redis-queue
        image: redis:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-queue-config
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
      volumes:
      - name: redis-queue-config
        configMap:
          name: redis-queue-configmap
